org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
fabric.loom.override-loom-version-check=true

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
fabric_version=0.92.2+1.20.1

# ---- this addon --------------------------------------------------------------
mod_version=1.0.1
maven_group=Glaxium.POV
archives_base_name=BBS-POV
bbs_jar=bbs-2.7-1.20.1.jar
